### PR TITLE
Translate Docs to simplified Chinese 

### PR DESCRIPTION
**Pull request by Darkluna999**
Translated Docs to simplified Chinese, and you may need to change some file tree for this...

### CODE REVIEW

**Comment by Darkluna999** [comment]
Translate Docs to simplified Chinese, and you may need to change some file tree for this....

**Comment by Vinzent03** [comment]
Hey, thank you very much for that translation. I've moved the files a bit to use docusaurus language switcher and some default translations of buttons like `Next` and `Previous`.

Do you want to translate the footer as well? You would need to change the message fields in `docs/i18n/zh-CN/docusaurus-theme-classic/footer.json`

**Comment by Darkluna999** [comment]
> Hey, thank you very much for that translation. I've moved the files a bit to use docusaurus language switcher and some default translations of buttons like `Next` and `Previous`.
> 
> Do you want to translate the footer as well? You would need to change the message fields in `docs/i18n/zh-CN/docusaurus-theme-classic/footer.json`

Sure, amd it's ready now...

**Comment by Vinzent03** [comment]
Thank you very much!

**Pull request merged**
