### PR TITLE
Add Search & Remove Feature

### PR DESCRIPTION
**Pull request by sigmoid-azoth**
Needed a way to remove query data rather than replace it. I'm a little new to pull requests so please let me know if I missed anything.

### CODE REVIEW

**Comment by Vinzent03** [comment]
Looks pretty good. But since your implementation is just replacing everything with an empty string, wouldn't it be better to support entering an empty replace string instead of adding a new parameter to remove? That way you an still use search and replace parameters.

**Comment by sigmoid-azoth** [comment]
> 
> 
> Looks pretty good. But since your implementation is just replacing everything with an empty string, wouldn't it be better to support entering an empty replace string instead of adding a new parameter to remove? That way you an still use search and replace parameters.

Your suggestion is what I would prefer but I wasn't able to implement it when I tried. I think that implementation would require an escape character for when users want to replace matches with literal "" or ''.

If you would prefer to reject my merge in favor of your suggestion, I'm okay with that.

**Comment by Vinzent03** [comment]
Oh, you mean you would have to specify it like this `replace=""`? This would replace it with `""`. You can just use `replace=`. But this doesn't work at the moment because of `if(parameters.replace)`. An empty string doesn't pass this statement. Honestly, I would like to reject this pr. Nevertheless, thanks for your will to contribute. Will fix this bug this evening.

**Comment by Vinzent03** [comment]
Fixed in new [release](https://github.com/Vinzent03/obsidian-advanced-uri/releases/tag/1.8.1)

**Pull request closed without merging**
